using PeopleHub.Helpers;
using PeopleHub.Models;

namespace PeopleHub.Services
{
    // The mock data is generated by ~300 lines of random rolls. If one of those
    // rolls is wrong the API still returns 200 OK — it just returns numbers that
    // are quietly nonsense (attendance before someone was hired, a check-out
    // before the check-in, an Infinity% on a dashboard card).
    //
    // This runs once at startup in Development and throws if any of that is
    // true, so a broken seed fails on `dotnet run` instead of in a card.
    public static class SeedSelfCheck
    {
        public static void Verify(
            IEmployeeService employeeService,
            IAttendanceService attendanceService,
            IRequestService requestService)
        {
            var staff = employeeService.GetAll();

            Require(staff.Count == EmployeeService.SeedCount,
                $"expected {EmployeeService.SeedCount} employees, got {staff.Count}");

            Require(staff.All(e => e.HireDate.Date >= EmployeeService.CompanyFoundedOn
                                && e.HireDate.Date <= DateTime.Today),
                $"hire dates must fall between {EmployeeService.CompanyFoundedOn:yyyy-MM-dd} and today");

            var hiredOn = staff.ToDictionary(e => e.Id, e => e.HireDate.Date);

            // Empty query = no filters = every record.
            var attendance = attendanceService.Filter(new AttendanceQuery());

            Require(attendance.Count > 0, "no attendance was generated");

            Require(attendance.All(r => DateRanges.IsWorkday(r.Date)),
                "attendance was generated on a non-working day (Fri/Sat)");

            Require(attendance.All(r => hiredOn.ContainsKey(r.EmployeeId) && r.Date >= hiredOn[r.EmployeeId]),
                "attendance exists for a day before the employee was hired");

            Require(attendance.All(r => r.CheckIn is null || r.CheckOut is null || r.CheckOut > r.CheckIn),
                "an attendance row checks out before it checks in");

            Require(attendance
                    .Where(r => r.Status is AttendanceStatus.Absent or AttendanceStatus.OnLeave)
                    .All(r => r.CheckIn is null && r.CheckOut is null),
                "an absent / on-leave row still has a clock-in time");

            var requests = requestService.GetAll();

            Require(requests.Count > 0, "no requests were generated");

            Require(requests.All(r => hiredOn.ContainsKey(r.EmployeeId)),
                "a request points at an employee that does not exist");

            Require(requests.All(r => r.EndDate.Date >= r.StartDate.Date),
                "a request ends before it starts");

            Require(requests.All(r => r.SubmittedAt.Date >= hiredOn[r.EmployeeId]),
                "a request was submitted before the employee was hired");

            Require(requests.All(r => r.Status != RequestStatus.Pending || r.ReviewedAt is null),
                "a pending request already has a review date");

            // Every dashboard card divides by a previous value — none of them may
            // come back as NaN or Infinity.
            TrendStat[] stats =
            {
                employeeService.GetHeadcountTrend(),
                employeeService.GetPayrollTrend(),
                attendanceService.GetMonthlyRateTrend(DateTime.Today)
            };

            Require(stats.All(s => !double.IsNaN(s.ChangePercent) && !double.IsInfinity(s.ChangePercent)),
                "a dashboard trend produced NaN or Infinity");
        }

        private static void Require(bool condition, string message)
        {
            if (!condition) throw new InvalidOperationException($"Seed self-check failed: {message}.");
        }
    }
}
